### ISSUE TITLE
Is sykmeldingArbeidsgiver.xsd up to date

### ISSUE THREAD

**Issue by mariusbartkevicius** [navikt/syfo-xml-codegen#11]
Hi,

does sykmeldingArbeidsgiver/src/main/xsd/sykmeldingArbeidsgiver.xsd is up to date to current version used?
Because I see it missing some stuff (at least what I have found: 'stillingsprosent' and 'naermesteLeder' are missing). Have you the newest version of xsd?

**Comment by andreasDev** [comment]
Yes it is up to date. There was an error were stillingsprosent and naermesteLeder was added to the xml in some cases.
